export interface PartPhysics {
  mass: number;
  size: [number, number];
  spriteSize?: [number, number];
}

export interface ThrusterCot {
  cot: [number, number, number][];
  thrust: number;
  boostoff?: number;
}

export const partPhysics: Record<string, PartPhysics> = {
  "cosmoteer.airlock": { mass: 1, size: [1, 1] },
  "cosmoteer.armor_1x2_wedge": { mass: 3, size: [1, 2] },
  "cosmoteer.armor_1x3_wedge": { mass: 4.5, size: [1, 3] },
  "cosmoteer.armor_2x1": { mass: 6, size: [2, 1] },
  "cosmoteer.armor_structure_hybrid_1x1": { mass: 1.5, size: [1, 1] },
  "cosmoteer.armor_structure_hybrid_1x2": { mass: 3, size: [1, 2] },
  "cosmoteer.armor_structure_hybrid_1x3": { mass: 4.5, size: [1, 3] },
  "cosmoteer.armor_structure_hybrid_tri": { mass: 1, size: [1, 1] },
  "cosmoteer.armor_tri": { mass: 0.75, size: [1, 1] },
  "cosmoteer.armor_wedge": { mass: 1.5, size: [1, 1] },
  "cosmoteer.armor": { mass: 3, size: [1, 1] },
  "cosmoteer.cannon_deck": { mass: 27.07, size: [4, 5], spriteSize: [4, 7] },
  "cosmoteer.cannon_large": { mass: 12.29, size: [3, 2], spriteSize: [3, 5] },
  "cosmoteer.cannon_med": { mass: 4.44, size: [2, 1], spriteSize: [2, 3] },
  "cosmoteer.chaingun_magazine": { mass: 2, size: [1, 2] },
  "cosmoteer.chaingun": { mass: 39.79, size: [3, 5], spriteSize: [3, 7] },
  "cosmoteer.control_room_large": { mass: 16, size: [4, 4] },
  "cosmoteer.control_room_med": { mass: 9, size: [3, 3] },
  "cosmoteer.control_room_small": { mass: 4, size: [2, 2] },
  "cosmoteer.conveyor": { mass: 1, size: [1, 1] },
  "cosmoteer.corridor": { mass: 1, size: [1, 1] },
  "cosmoteer.crew_quarters_large": { mass: 12, size: [3, 4] },
  "cosmoteer.crew_quarters_med": { mass: 4, size: [2, 2] },
  "cosmoteer.crew_quarters_small": { mass: 2, size: [1, 2] },
  "cosmoteer.disruptor": { mass: 3.48, size: [1, 3], spriteSize: [1, 5] },
  "cosmoteer.engine_room": { mass: 9, size: [3, 3] },
  "cosmoteer.explosive_charge": { mass: 1, size: [1, 1] },
  "cosmoteer.factory_ammo": { mass: 4, size: [2, 2] },
  "cosmoteer.factory_coil": { mass: 9, size: [3, 3] },
  "cosmoteer.factory_coil2": { mass: 12, size: [4, 3] },
  "cosmoteer.factory_diamond": { mass: 6, size: [2, 3] },
  "cosmoteer.factory_emp": { mass: 12, size: [3, 4] },
  "cosmoteer.factory_he": { mass: 9, size: [3, 3] },
  "cosmoteer.factory_mine": { mass: 12, size: [4, 3] },
  "cosmoteer.factory_nuke": { mass: 16, size: [4, 4] },
  "cosmoteer.factory_processor": { mass: 9, size: [3, 3] },
  "cosmoteer.factory_steel": { mass: 16, size: [4, 4] },
  "cosmoteer.factory_thermal": { mass: 9, size: [3, 3] },
  "cosmoteer.factory_tristeel": { mass: 16, size: [4, 4] },
  "cosmoteer.factory_uranium": { mass: 12, size: [3, 4] },
  "cosmoteer.fire_extinguisher": { mass: 1, size: [1, 1] },
  "cosmoteer.flak_cannon_large": { mass: 16.77, size: [3, 6], spriteSize: [3, 8] },
  "cosmoteer.heat_exchanger": { mass: 1, size: [1, 1] },
  "cosmoteer.heat_pipe_adaptive_structure": { mass: 1, size: [1, 1] },
  "cosmoteer.heat_pipe_adaptive": { mass: 1, size: [1, 1] },
  "cosmoteer.heat_pipe_crossing": { mass: 1, size: [1, 1] },
  "cosmoteer.hyperdrive_beacon": { mass: 17.13, size: [4, 4] },
  "cosmoteer.hyperdrive_large": { mass: 16, size: [4, 4] },
  "cosmoteer.hyperdrive_med": { mass: 9, size: [3, 3] },
  "cosmoteer.hyperdrive_small": { mass: 4, size: [2, 2] },
  "cosmoteer.ion_beam_emitter": { mass: 8, size: [2, 4], spriteSize: [2, 5] },
  "cosmoteer.ion_beam_prism": { mass: 7.7, size: [2, 2], spriteSize: [2, 2.5] },
  "cosmoteer.laser_blaster_large": { mass: 7.68, size: [2, 3], spriteSize: [2, 6] },
  "cosmoteer.laser_blaster_small": { mass: 2.5, size: [1, 2], spriteSize: [1, 4] },
  "cosmoteer.manipulator_beam_emitter": { mass: 4, size: [2, 2] },
  "cosmoteer.mining_laser_small": { mass: 7.4, size: [2, 3] },
  "cosmoteer.missile_launcher": { mass: 8, size: [2, 3], spriteSize: [2, 4] },
  "cosmoteer.point_defense": { mass: 1.19, size: [1, 1], spriteSize: [1, 2] },
  "cosmoteer.power_storage": { mass: 4, size: [2, 2] },
  "cosmoteer.radiator": { mass: 3, size: [1, 3] },
  "cosmoteer.railgun_accelerator": { mass: 36, size: [2, 3] },
  "cosmoteer.railgun_launcher": { mass: 36, size: [2, 3], spriteSize: [2, 4] },
  "cosmoteer.railgun_loader": { mass: 24, size: [2, 3] },
  "cosmoteer.reactor_large": { mass: 16, size: [4, 4] },
  "cosmoteer.reactor_med": { mass: 9, size: [3, 3] },
  "cosmoteer.reactor_small": { mass: 4, size: [2, 2] },
  "cosmoteer.resonance_beam_turret": { mass: 21.54, size: [4, 4], spriteSize: [4, 5] },
  "cosmoteer.resource_collector": { mass: 4, size: [2, 2] },
  "cosmoteer.roof_headlight": { mass: 1, size: [1, 1] },
  "cosmoteer.roof_light": { mass: 1, size: [1, 1] },
  "cosmoteer.sensor_array": { mass: 11.54, size: [3, 3] },
  "cosmoteer.shield_gen_large": { mass: 12.65, size: [3, 6] },
  "cosmoteer.shield_gen_small": { mass: 6, size: [2, 2], spriteSize: [2, 3] },
  "cosmoteer.storage_2x2": { mass: 4, size: [2, 2] },
  "cosmoteer.storage_3x2": { mass: 6, size: [3, 2] },
  "cosmoteer.storage_3x3": { mass: 9, size: [3, 3] },
  "cosmoteer.storage_4x3": { mass: 12, size: [4, 3] },
  "cosmoteer.storage_4x4": { mass: 16, size: [4, 4] },
  "cosmoteer.structure_1x2_wedge": { mass: 0.33, size: [1, 2] },
  "cosmoteer.structure_1x3_wedge": { mass: 0.5, size: [1, 3] },
  "cosmoteer.structure_tri": { mass: 0.08, size: [1, 1] },
  "cosmoteer.structure_wedge": { mass: 0.17, size: [1, 1] },
  "cosmoteer.structure": { mass: 1 / 3, size: [1, 1] },
  "cosmoteer.thermal_amplification_pump": { mass: 3, size: [1, 3] },
  "cosmoteer.thermal_battery": { mass: 4, size: [2, 2] },
  "cosmoteer.thermal_dilation_pump": { mass: 4, size: [2, 2] },
  "cosmoteer.thruster_boost": { mass: 8.88, size: [2, 3], spriteSize: [2, 5] },
  "cosmoteer.thruster_huge": { mass: 11, size: [3, 3], spriteSize: [3, 5] },
  "cosmoteer.thruster_large": { mass: 4.99, size: [2, 2], spriteSize: [2, 3] },
  "cosmoteer.thruster_med": { mass: 2.45, size: [1, 2], spriteSize: [1, 3] },
  "cosmoteer.thruster_rocket_battery": { mass: 2, size: [1, 2] },
  "cosmoteer.thruster_rocket_extender": { mass: 6, size: [3, 2] },
  "cosmoteer.thruster_rocket_nozzle": { mass: 14.4, size: [3, 4], spriteSize: [3, 5] },
  "cosmoteer.thruster_small_2way": { mass: 1.61, size: [1, 1], spriteSize: [2, 2] },
  "cosmoteer.thruster_small_3way": { mass: 1.91, size: [1, 1], spriteSize: [3, 2] },
  "cosmoteer.thruster_small": { mass: 1.3, size: [1, 1], spriteSize: [1, 2] },
  "cosmoteer.tractor_beam_emitter": { mass: 32.07, size: [5, 5] },
};

export const thrusterData: Record<string, ThrusterCot> = {
  "cosmoteer.thruster_small": { cot: [[0.5, 1.5, 0]], thrust: 400 },
  "cosmoteer.thruster_med": { cot: [[0.5, 2.5, 0]], thrust: 1300 },
  "cosmoteer.thruster_large": { cot: [[1, 2.5, 0]], thrust: 3600 },
  "cosmoteer.thruster_boost": { cot: [[1, 4.5, 0]], thrust: 9600, boostoff: 3600 },
  "cosmoteer.thruster_huge": { cot: [[1.5, 3.5, 0]], thrust: 8000 },
  "cosmoteer.thruster_small_2way": { cot: [[0.5, 1.5, 0], [1.5, 0.5, 3]], thrust: 400 },
  "cosmoteer.thruster_small_3way": {
    cot: [[0.5, 1.5, 0], [1.5, 0.5, 3], [-0.5, 0.5, 1]],
    thrust: 400,
  },
  "cosmoteer.thruster_rocket_nozzle": { cot: [[1.5, 4, 0]], thrust: 10000 },
  "cosmoteer.thruster_rocket_extender": { cot: [[1.5, 1, 0]], thrust: 10000 },
};

export const thrusterDataOC: Record<string, ThrusterCot> = {
  "cosmoteer.thruster_small": { cot: [[0.5, 1.5, 0]], thrust: 1600 },
  "cosmoteer.thruster_med": { cot: [[0.5, 2.5, 0]], thrust: 3400 },
  "cosmoteer.thruster_large": { cot: [[1, 2.5, 0]], thrust: 7200 },
  "cosmoteer.thruster_boost": { cot: [[1, 4.5, 0]], thrust: 24000, boostoff: 7200 },
  "cosmoteer.thruster_huge": { cot: [[1.5, 3.5, 0]], thrust: 14000 },
  "cosmoteer.thruster_small_2way": { cot: [[0.5, 1.5, 0], [1.5, 0.5, 3]], thrust: 1600 },
  "cosmoteer.thruster_small_3way": {
    cot: [[0.5, 1.5, 0], [1.5, 0.5, 3], [-0.5, 0.5, 1]],
    thrust: 1600,
  },
  "cosmoteer.thruster_rocket_nozzle": { cot: [[1.5, 4, 0]], thrust: 10500 },
  "cosmoteer.thruster_rocket_extender": { cot: [[1.5, 1, 0]], thrust: 10500 },
};
