export const partTagMap: Record<string, string> = {
  "cosmoteer.cannon_med": "cannon",
  "cosmoteer.cannon_deck": "deck_cannon",
  "cosmoteer.flak_cannon_large": "flak_battery",
  "cosmoteer.cannon_large": "large_cannon",
  "cosmoteer.railgun_launcher": "railgun",
  "cosmoteer.factory_emp": "factories",
  "cosmoteer.factory_he": "factories",
  "cosmoteer.factory_mine": "factories",
  "cosmoteer.factory_nuke": "factories",
  "cosmoteer.factory_thermal": "factories",
  "cosmoteer.disruptor": "disruptors",
  "cosmoteer.laser_blaster_large": "heavy_laser",
  "cosmoteer.ion_beam_emitter": "ion_beam",
  "cosmoteer.ion_beam_prism": "ion_prism",
  "cosmoteer.laser_blaster_small": "laser",
  "cosmoteer.mining_laser_small": "mining_laser",
  "cosmoteer.point_defense": "point_defense",
  "cosmoteer.thruster_boost": "boost_thruster",
  "cosmoteer.airlock": "airlock",
  "cosmoteer.factory_coil": "campaign_factories",
  "cosmoteer.factory_coil2": "campaign_factories",
  "cosmoteer.factory_diamond": "campaign_factories",
  "cosmoteer.factory_processor": "campaign_factories",
  "cosmoteer.factory_steel": "campaign_factories",
  "cosmoteer.factory_tristeel": "campaign_factories",
  "cosmoteer.factory_uranium": "campaign_factories",
  "cosmoteer.explosive_charge": "explosive_charges",
  "cosmoteer.fire_extinguisher": "fire_extinguisher",
  "cosmoteer.reactor_large": "large_reactor",
  "cosmoteer.shield_gen_large": "large_shield",
  "cosmoteer.reactor_med": "medium_reactor",
  "cosmoteer.sensor_array": "sensor",
  "cosmoteer.hyperdrive_small": "small_hyperdrive",
  "cosmoteer.reactor_small": "small_reactor",
  "cosmoteer.shield_gen_small": "small_shield",
  "cosmoteer.tractor_beam_emitter": "tractor_beams",
  "cosmoteer.hyperdrive_beacon": "hyperdrive_relay",
  "cosmoteer.chaingun": "chaingun",
  "cosmoteer.thruster_rocket_battery": "rocket_thruster",
  "cosmoteer.thruster_rocket_extender": "rocket_thruster",
  "cosmoteer.thruster_rocket_nozzle": "rocket_thruster",
  "cosmoteer.hyperdrive_large": "large_hyperdrive",
  "cosmoteer.resonance_beam_turret": "resonance_beam_turret",
};

export const missileTagMap: Record<number, string> = {
  0: "he_missiles",
  1: "emp_missiles",
  2: "nukes",
  3: "mines",
  4: "thermal_missiles",
};
