# The size parameter is the size of the tiles, it doesn't care about turrets or engines
parts={
        "cosmoteer.corridor":{"mass":1, "size":(1,1)},
        "cosmoteer.structure":{"mass":1/3, "size":(1,1)},
        "cosmoteer.structure_wedge":{"mass":0.17, "size":(1,1)},
        "cosmoteer.structure_1x2_wedge":{"mass":0.33, "size":(1,2)},
        "cosmoteer.structure_1x3_wedge":{"mass":0.5, "size":(1,3)},
        "cosmoteer.structure_tri":{"mass":0.08, "size":(1,1)},
        "cosmoteer.laser_blaster_small":{"mass":2.5, "size":(1,2), "sprite_size":(1,4)},
        "cosmoteer.laser_blaster_large":{"mass":7.68, "size":(2,3), "sprite_size":(2,6)},
        "cosmoteer.disruptor":{"mass":3.48, "size":(1,3), "sprite_size":(1,5)},
        "cosmoteer.ion_beam_emitter":{"mass":8, "size":(2,4), "sprite_size":(2,5)},
        "cosmoteer.resource_collector":{"mass":4, "size":(2,2)},
        "cosmoteer.ion_beam_prism":{"mass":7.7, "size":(2,2), "sprite_size":(2,2.5)},
        "cosmoteer.tractor_beam_emitter":{"mass":32.07, "size":(5,5)},
        "cosmoteer.point_defense":{"mass":1, "size":(1,1), "sprite_size":(1,2)},
        "cosmoteer.mining_laser_small":{"mass":7.4, "size":(2,3)},
        "cosmoteer.cannon_med":{"mass":4.44, "size":(2,1), "sprite_size":(2,3)},
        "cosmoteer.sensor_array":{"mass":11.54, "size":(3,3)},
        "cosmoteer.cannon_large":{"mass":12.29, "size":(3,2), "sprite_size":(3,5)},
        "cosmoteer.hyperdrive_beacon":{"mass":17.13, "size":(4,4)},
        "cosmoteer.cannon_deck":{"mass":27.07, "size":(4,5), "sprite_size":(4,7)},
        "cosmoteer.explosive_charge":{"mass":1, "size":(1,1)},
        "cosmoteer.roof_light":{"mass":1, "size":(1,1)},
        "cosmoteer.missile_launcher":{"mass":6, "size":(2,3), "sprite_size":(2,4)},
        "cosmoteer.roof_headlight":{"mass":1, "size":(1,1)},
        "cosmoteer.railgun_loader":{"mass":24, "size":(2,3)},
        "cosmoteer.armor_structure_hybrid_1x1":{"mass":1.5, "size":(1,1)},
        "cosmoteer.armor_structure_hybrid_1x2":{"mass":3, "size":(1,2)},
        "cosmoteer.railgun_accelerator":{"mass":36, "size":(2,3)},
        "cosmoteer.armor_structure_hybrid_1x3":{"mass":4.5, "size":(1,3)},
        "cosmoteer.armor_structure_hybrid_tri":{"mass":1, "size":(1,1)},
        "cosmoteer.railgun_launcher":{"mass":36, "size":(2,3), "sprite_size":(2,4)},
        "cosmoteer.armor":{"mass":3, "size":(1,1)},
        "cosmoteer.armor_2x1":{"mass":6, "size":(2,1)},
        "cosmoteer.flak_cannon_large":{"mass":16.77, "size":(3,6), "sprite_size":(3,8)},
        "cosmoteer.armor_wedge":{"mass":1.5, "size":(1,1)},
        "cosmoteer.armor_1x2_wedge":{"mass":3, "size":(1,2)},
        "cosmoteer.shield_gen_small":{"mass":6, "size":(2,2), "sprite_size":(2,3)},
        "cosmoteer.armor_1x3_wedge":{"mass":4.5, "size":(1,3)},
        "cosmoteer.armor_tri":{"mass":0.75, "size":(1,1)},
        "cosmoteer.shield_gen_large":{"mass":12.65, "size":(3,6)},
        "cosmoteer.thruster_small":{"mass":1.3, "size":(1,1), "sprite_size":(1,2)},
        "cosmoteer.thruster_med":{"mass":2.45, "size":(1,2), "sprite_size":(1,3)},
        "cosmoteer.thruster_large":{"mass":4.99, "size":(2,2), "sprite_size":(2,3)},
        "cosmoteer.thruster_boost":{"mass":8.88, "size":(2,3), "sprite_size":(2,5)},
        "cosmoteer.fire_extinguisher":{"mass":1, "size":(1,1)},
        "cosmoteer.thruster_huge":{"mass":11, "size":(3,3), "sprite_size":(3,5)},
        "cosmoteer.control_room_small":{"mass":4, "size":(2,2)},
        "cosmoteer.control_room_med":{"mass":9, "size":(3,3)},
        "cosmoteer.thruster_small_2way":{"mass":1.61, "size":(1,1), "sprite_size":(2,2)},
        "cosmoteer.control_room_large":{"mass":16, "size":(4,4)},
        "cosmoteer.thruster_small_3way":{"mass":1.91, "size":(1,1), "sprite_size":(3,2)},
        "cosmoteer.hyperdrive_small":{"mass":4, "size":(2,2)},
        "cosmoteer.engine_room":{"mass":9, "size":(3,3)},
        "cosmoteer.crew_quarters_small":{"mass":2, "size":(1,2)},
        "cosmoteer.crew_quarters_med":{"mass":4, "size":(2,2)},
        "cosmoteer.airlock":{"mass":1, "size":(1,1)},
        "cosmoteer.conveyor":{"mass":1, "size":(1,1)},
        "cosmoteer.reactor_small":{"mass":4, "size":(2,2)},
        "cosmoteer.reactor_med":{"mass":9, "size":(3,3)},
        "cosmoteer.reactor_large":{"mass":16, "size":(4,4)},
        "cosmoteer.power_storage":{"mass":4, "size":(2,2)},
        "cosmoteer.factory_ammo":{"mass":4, "size":(2,2)},
        "cosmoteer.factory_he":{"mass":9, "size":(3,3)},
        "cosmoteer.factory_emp":{"mass":12, "size":(3,4)},
        "cosmoteer.factory_nuke":{"mass":16, "size":(4,4)},
        "cosmoteer.factory_mine":{"mass":12, "size":(4,3)},
        "cosmoteer.factory_steel":{"mass":16, "size":(4,4)},
        "cosmoteer.factory_coil":{"mass":9, "size":(3,3)},
        "cosmoteer.factory_coil2":{"mass":12, "size":(4,3)},
        "cosmoteer.factory_tristeel":{"mass":16, "size":(4,4)},
        "cosmoteer.factory_diamond":{"mass":6, "size":(2,3)},
        "cosmoteer.factory_processor":{"mass":9, "size":(3,3)},
        "cosmoteer.factory_uranium":{"mass":12, "size":(3,4)},
        "cosmoteer.storage_2x2":{"mass":4, "size":(2,2)},
        "cosmoteer.storage_3x2":{"mass":6, "size":(3,2)},
        "cosmoteer.storage_3x3":{"mass":9, "size":(3,3)},
        "cosmoteer.storage_4x3":{"mass":12, "size":(4,3)},
        "cosmoteer.storage_4x4":{"mass":16, "size":(4,4)},
}

thruster_data={
        "cosmoteer.thruster_small":{"cot":((0.5,1.5,0),),"thrust":400},
        "cosmoteer.thruster_med":{"cot":((0.5,2.5,0),),"thrust":1200},
        "cosmoteer.thruster_large":{"cot":((1,2.5,0),),"thrust":3200},
        "cosmoteer.thruster_boost":{"cot":((1,4.5,0),),"thrust":3200},
        "cosmoteer.thruster_huge":{"cot":((1.5,3.5,0),),"thrust":8000},
        "cosmoteer.thruster_small_2way":{"cot":((0.5,1.5,0),(1.5,0.5,3)),"thrust":400},
        "cosmoteer.thruster_small_3way":{"cot":((0.5,1.5,0),(1.5,0.5,3),(-0.5,0.5,1)),"thrust":400},
}